Update order of vertexes, and add closing vertex for Oracle.
opencadc/tap pull request #142
Opened 2023-02-24 18:35 UTC by at88mph

Ensure Polygon vertices are in counter-clockwise order.
Ensure Polygons are closed before sending to Oracle.

2023-02-28 15:17 UTC, at88mph commented
I've included a namespace fix for the table reader as well, but it may not be the right way to fix it.

2023-03-03 22:10 UTC, pdowler requested changes

2023-03-03 22:10 UTC, pdowler commented on cadc-tap-server-oracle/src/main/java/ca/nrc/cadc/tap/parser/region/function/OraclePolygon.java
> +    private void ensureCounterClockwise() {
I assume the algorithm here is for a polygon on a flat plane, so is approximate. I don't know what "edgeSum" is but this looks less complex than the code in caom2 which does this by computing the area via triangulation. 

Is this calculation going to work in edge cases:
1. near or includes the pole
2. overlaps the meridian (longitude=0) so some vertices have longitude near 360 and others near 0
4. is is larger than half the sphere

It's probably OK to not support #3 (for now), but it should be detected and rejected. 1 and 2 need to be taken into account somehow.

2023-03-03 22:10 UTC, pdowler commented on cadc-tap/src/main/java/ca/nrc/cadc/vosi/TableReader.java
> +    private static final String TAP_TYPE = "vs:TAPType";
This is the thing I ran into and fixed more correctly than hard-coding the prefix. You can discard this change and I'll push my PR to the repo (was going to do yours first until they overlapped).

2023-03-04 14:05 UTC, at88mph commented on cadc-tap/src/main/java/ca/nrc/cadc/vosi/TableReader.java
> +    private static final String TAP_TYPE = "vs:TAPType";
Done.

2023-03-04 14:08 UTC, at88mph commented on cadc-tap-server-oracle/src/main/java/ca/nrc/cadc/tap/parser/region/function/OraclePolygon.java
> +    private void ensureCounterClockwise() {
That's correct.  The sum of the edges indicates a clockwise direction if it's a positive number, and counter-clockwise if it's negative, and assumes a flat plane.  I hadn't realized it needed to be more complex than that, thanks.

2023-03-06 17:35 UTC, at88mph commented on cadc-tap-server-oracle/src/main/java/ca/nrc/cadc/tap/parser/region/function/OraclePolygon.java
> +    private void ensureCounterClockwise() {
Is the `GrahamScan` in CAOM-2 a place to start learning about how to handle those three cases?  Is this the "winding" method?

2025-03-13 17:31 UTC, pdowler commented on cadc-tap-server-oracle/src/main/java/ca/nrc/cadc/tap/parser/region/function/OraclePolygon.java
> +    private void ensureCounterClockwise() {
this is a really old PR that we seem to have dropped behind the desk... is this still needed or OBE?

2025-03-13 17:33 UTC, at88mph commented
I haven't seen any incorrect values as a result of _not_ having this for the time being.  I'll keep my branch around, but this PR is over two years old now, so I'll close it.

2025-03-13 17:33 UTC, closed without merging