youcat: code transfer from cadc internal repo and refactor
opencadc/tap pull request #144
Opened 2023-04-26 03:56 UTC by pdowler

2023-04-26 21:56 UTC, brianmajor requested changes

2023-04-26 21:56 UTC, brianmajor commented on youcat/README.md
> +in order to mangle queries on the *tap_schema* content. A service providing the
```suggestion
in order to inject group membership information into queries on the *tap_schema* content. A service providing the 
```

2023-04-26 21:56 UTC, brianmajor commented on youcat/README.md
> +This service uses the `cadc-tap-tmp` library to persist tap_upload tables and async results. It is currently
Maybe somehow make clear that this uploading is different than the user-table functions that youcat provides.

2023-04-27 20:46 UTC, pdowler commented on youcat/README.md
> +in order to mangle queries on the *tap_schema* content. A service providing the
fixed manually

2023-04-27 21:23 UTC, merged