CADC-13694 added created boolean column to tap_schema.tables
opencadc/tap pull request #173
Opened 2024-09-06 15:31 UTC by jburke-cadc

2024-09-09 16:51 UTC, pdowler requested changes

2024-09-09 16:51 UTC, pdowler commented on cadc-tap/src/main/java/ca/nrc/cadc/tap/schema/TableDesc.java
> +    public Boolean created;
Must use the same name everywhere, so this should be `apiCreated` given the other naming.

Normally, the field name and the column name would be exactly the same, but in the case of tap_schema the "underscore" database naming style is used, but at least camel-case to underscore is predictable (so column name `api_created` is a good enough match).

2024-09-09 16:51 UTC, pdowler commented on cadc-tap-schema/src/main/resources/postgresql/tap_schema11.sql
> +    api_created     integer,
after viewing this particular file, it is clear that we also need `SchemaDesc.apiCreated` for the same reasons. 

Currently, the value should be the value of the `createSchemaInDB` config item... if/when we make a change to support both modes and/or owner or admin removing a schema, we'll be glad we tracked this. A deployer could already change the config or deploy instances with different config values, so we need to start tracking this even if we don't support `DELETE /tables/{schema}`

reason: if someone can do something via api -- "create schema" -- then they should also be able to undo it -- and we'll need to know if that includes dropping schema in the db or not so we'll want to know if the service created it

2024-09-09 16:51 UTC, pdowler commented on cadc-tap-schema/build.gradle
> +version = '1.2.0'
this really should be 1.2.1 even though we never published 1.2.0 ... want to fully fix the past oops.

2024-09-09 16:51 UTC, pdowler commented on cadc-tap-schema/src/main/java/ca/nrc/cadc/tap/schema/TapSchemaDAO.java
> +            // created set only in a PUT
I'm not sure we need or want this distinction; there is no way to modify the value of `table.apiCreated` so it will be stable, but if we ever want to modify it we won't want to skip here. I think it is better to include all columns in the insert and update whether or not we expect a change. That way the DAO does what you tell it to do with the input TableDesc and doesn't make any decisions like this.

(yes, this DAO class currently persists TapPermission columns separately in an update-only mode, but I plan to fix that later)

2024-09-09 21:22 UTC, jburke-cadc commented on cadc-tap/src/main/java/ca/nrc/cadc/tap/schema/TableDesc.java
> +    public Boolean created;
Updated the field name to apiCreated.

2024-09-09 21:23 UTC, jburke-cadc commented on cadc-tap-schema/build.gradle
> +version = '1.2.0'
Updated.

2024-09-09 21:24 UTC, jburke-cadc commented on cadc-tap-schema/src/main/java/ca/nrc/cadc/tap/schema/TapSchemaDAO.java
> +            // created set only in a PUT
Updated.

2024-09-10 21:52 UTC, pdowler approved these changes

2024-09-10 21:52 UTC, merged