CADC-13577 add an ID attribute to VOSI-table serialization
opencadc/tap pull request #183
Opened 2024-12-19 21:55 UTC by jburke-cadc

- doesn't include the cadc-tap-schema updates to rename tap_schema.columns11 id column to column_id, should it?
- the namespace is TBD

2025-01-13 19:28 UTC, pdowler reviewed
The name of the upgrade file and the comment suggest these changes are in 1.2.2 but the currently released cadc-tap-schema is 1.2.3 ... head of main has 1.2.4 already because of previous un-released work (VOSI-tables output votable).

This PR has changed column name but I do not see any code changes. There must be changes in InitDatabaseTS and in TapSchemaDAO (which references the `id` column). The TapSchemaDAOTest intTest will run InitDatabaseTS to either create or upgrade the tap_schema structure and you make sure to test both of those.

2025-01-14 20:21 UTC, jburke-cadc commented on cadc-tap/build.gradle
> +sourceSets {
Using Gradle 6.8.3.
Removed the sourceSets from build.gradle, and it builds and test pass.

2025-01-14 20:27 UTC, pdowler approved these changes

2025-02-26 04:34 UTC, pdowler requested changes

2025-02-26 04:34 UTC, pdowler commented on cadc-tap-schema/src/main/resources/postgresql/tap_schema.upgrade-1.2.5.sql
> +create unique index column_id_unique_not_null on tap_schema.columns11 (column_id) where column_id is not null;
index name doesn't need all the details and I found other cases where it was necessary to put the table name in the index name so it could be uniquely referenced (eg in a later drop index)  (eg the uws db schema)

so maybe something like `columns_column_id`??

2025-03-11 20:44 UTC, pdowler approved these changes

2025-03-11 20:44 UTC, merged